name: prod
variables:
  - secret: true
    name: BASE_URL
  - secret: true
    name: API_KEY
  - secret: true
    name: HOST
  - secret: true
    name: DATABASE
  - secret: true
    name: LOGIN
  - secret: true
    name: PASSWORD
