name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  chrome-extension:
    name: Build & Test Angular
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        working-directory: frontend
        run: npm ci

      - name: Build
        working-directory: frontend
        run: npm run build

#      TODO: enable tests
#      - name: Test
#        working-directory: frontend
#        run: npm test -- --watch=false --browsers=ChromeHeadless
